/*
 * Bowie — P2P Internet Sharing Tool (Repo: bowie)
 * Copyright (C) 2026 ASBM Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * ============================================================================
 * BOWIE — SIGN
 * ============================================================================
 *
 * Ed25519 digital signatures.
 *
 * This header declares the signature functions Bowie uses. The
 * implementation is backed by OpenSSL.
 *
 * ----------------------------------------------------------------------------
 * What this file does NOT do
 * ----------------------------------------------------------------------------
 *
 *   - No key generation. A keypair is generated by keypair.h.
 *   - No encryption. Public-key encryption is not used in
 *     Bowie; symmetric encryption is in cipher.h.
 *   - No certificate parsing. Bowie does not use X.509.
 *   - No streaming API. Every function signs or verifies a
 *     complete buffer.
 *   - No allocation. Every function writes to a caller-supplied
 *     output buffer.
 *
 * ----------------------------------------------------------------------------
 * Design notes
 * ----------------------------------------------------------------------------
 *
 * Ed25519 is the signature algorithm. It is used for:
 *
 *   - Proof of Ownership (PoO): the owner signs a challenge
 *     with their private key; a verifier checks the signature
 *     against the owner's public key.
 *
 *   - Permission grants: the owner signs a grant with their
 *     private key; a verifier checks the signature.
 *
 *   - Session challenges: a peer signs a random challenge with
 *     their private key; the peer on the other side checks it.
 *
 * Ed25519 keys are 32 bytes for the public key and 64 bytes
 * for the private key. OpenSSL's Ed25519 private key is 64
 * bytes: the first 32 bytes are the seed, the second 32 bytes
 * are the public key. The functions here use the full 64-byte
 * form, which is what EVP_PKEY expects.
 *
 * A signature is 64 bytes.
 *
 * The signature functions are deterministic for a fixed key
 * and message. Ed25519 signatures are deterministic by design,
 * so a test that signs twice and compares the two signatures
 * is a valid test of the implementation.
 *
 * ----------------------------------------------------------------------------
 * Dependencies
 * ----------------------------------------------------------------------------
 *
 *   <stdint.h>                    uint8_t
 *   <stddef.h>                    size_t
 *   "bowie/err.h"                 bowie_error_t
 *   <openssl/evp.h>               EVP_PKEY, EVP_MD_CTX
 * ============================================================================
 */

#ifndef BOWIE_CRYPTO_SIGN_H
#define BOWIE_CRYPTO_SIGN_H

#include <stdint.h>
#include <stddef.h>

#include "bowie/err.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * ============================================================================
 * CONSTANTS
 * ============================================================================
 */

#define BOWIE_SIGN_PUBLIC_LEN    32
#define BOWIE_SIGN_PRIVATE_LEN   64
#define BOWIE_SIGN_SIGNATURE_LEN 64

/*
 * ============================================================================
 * TYPES
 * ============================================================================
 *
 * Fixed-size value types. A key or a signature can be copied
 * and compared without allocation.
 */

typedef struct bowie_sign_public {
    uint8_t bytes[BOWIE_SIGN_PUBLIC_LEN];
} bowie_sign_public_t;

typedef struct bowie_sign_private {
    uint8_t bytes[BOWIE_SIGN_PRIVATE_LEN];
} bowie_sign_private_t;

typedef struct bowie_sign_signature {
    uint8_t bytes[BOWIE_SIGN_SIGNATURE_LEN];
} bowie_sign_signature_t;

/*
 * ============================================================================
 * SIGN
 * ============================================================================
 */

/*
 * Sign a message with an Ed25519 private key.
 *
 * On success, the 64-byte signature is written through out.
 *
 * Returns BOWIE_OK on success.
 * Returns BOWIE_ERR_NULL_ARG if private_key, msg, or out is
 *   NULL. A msg pointer with len == 0 is allowed.
 * Returns BOWIE_ERR_CRYPTO if the underlying library reports a
 *   failure.
 */
bowie_error_t bowie_sign_ed25519(
    const bowie_sign_private_t *private_key,
    const void *msg, size_t msg_len,
    bowie_sign_signature_t *out);

/*
 * Verify an Ed25519 signature.
 *
 * Returns BOWIE_OK if the signature is valid.
 * Returns BOWIE_ERR_NULL_ARG if public_key, msg, or signature
 *   is NULL. A msg pointer with len == 0 is allowed.
 * Returns BOWIE_ERR_SIGN_INVALID if the signature does not
 *   verify.
 * Returns BOWIE_ERR_CRYPTO if the underlying library reports a
 *   failure.
 */
bowie_error_t bowie_sign_ed25519_verify(
    const bowie_sign_public_t *public_key,
    const void *msg, size_t msg_len,
    const bowie_sign_signature_t *signature);

/*
 * ============================================================================
 * KEY DERIVATION
 * ============================================================================
 */

/*
 * Derive the public key from an Ed25519 private key.
 *
 * The private key is the 64-byte OpenSSL form (seed || public).
 * The public key is written through out.
 *
 * Returns BOWIE_OK on success.
 * Returns BOWIE_ERR_NULL_ARG if private_key or out is NULL.
 * Returns BOWIE_ERR_CRYPTO if the underlying library reports a
 *   failure.
 */
bowie_error_t bowie_sign_ed25519_public_from_private(
    const bowie_sign_private_t *private_key,
    bowie_sign_public_t *out);

#ifdef __cplusplus
}
#endif

#endif /* BOWIE_CRYPTO_SIGN_H */
