/*
 * Bowie — P2P Internet Sharing Tool (Repo: bowie)
 * Copyright (C) 2026 ASBM Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * ============================================================================
 * BOWIE — SIGN IMPLEMENTATION
 * ============================================================================
 *
 * Ed25519 digital signatures backed by OpenSSL.
 *
 * ----------------------------------------------------------------------------
 * What this file does NOT do
 * ----------------------------------------------------------------------------
 *
 *   - No key generation. A keypair is generated by keypair.c.
 *   - No encryption.
 *   - No certificate parsing.
 *   - No streaming API.
 *   - No allocation in the success path.
 *
 * ----------------------------------------------------------------------------
 * Design notes
 * ----------------------------------------------------------------------------
 *
 * The implementation uses the EVP interface with EVP_PKEY_ED25519.
 * This is the OpenSSL 3.0 interface for Ed25519. The older
 * EVP_DigestSign functions with ED25519 work, but the newer
 * EVP_PKEY_sign / EVP_PKEY_verify with no digest are the
 * recommended shape for a "pure" Ed25519 signature.
 *
 * An Ed25519 private key in OpenSSL is the 64-byte form: the
 * first 32 bytes are the seed, the second 32 bytes are the
 * public key. The function bowie_sign_ed25519_public_from_private
 * reads the second half directly. The sign and verify functions
 * use the full key through EVP_PKEY_new_raw_private_key and
 * EVP_PKEY_new_raw_public_key.
 *
 * Every EVP_PKEY and EVP_MD_CTX is created and freed inside the
 * function. There is no global state. The functions are safe
 * to call from any thread as long as the caller does not share
 * the input or output buffers between threads.
 *
 * The implementation is deterministic for a fixed key and
 * message. Ed25519 signatures are deterministic by design; the
 * nonce is derived from the private key and the message. A test
 * that signs twice and compares the two signatures is a valid
 * test of the implementation.
 *
 * ----------------------------------------------------------------------------
 * Dependencies
 * ----------------------------------------------------------------------------
 *
 *   <openssl/evp.h>              EVP_PKEY, EVP_MD_CTX,
 *                                EVP_PKEY_new_raw_private_key,
 *                                EVP_PKEY_new_raw_public_key,
 *                                EVP_PKEY_free,
 *                                EVP_MD_CTX_new, EVP_MD_CTX_free,
 *                                EVP_DigestSignInit,
 *                                EVP_DigestSign,
 *                                EVP_DigestVerifyInit,
 *                                EVP_DigestVerify,
 *                                EVP_PKEY_ED25519
 *   <openssl/err.h>              ERR_clear_error (optional)
 *   <string.h>                   memcpy
 *   "bowie/err.h"                error codes
 *   "crypto/sign.h"              the declarations
 * ============================================================================
 */

#include <openssl/evp.h>

#include <string.h>

#include "bowie/err.h"
#include "crypto/sign.h"

/*
 * ============================================================================
 * SIGN
 * ============================================================================
 */

bowie_error_t bowie_sign_ed25519(
    const bowie_sign_private_t *private_key,
    const void *msg, size_t msg_len,
    bowie_sign_signature_t *out)
{
    if (private_key == NULL || out == NULL) {
        return BOWIE_ERR_NULL_ARG;
    }
    if (msg == NULL && msg_len > 0u) {
        return BOWIE_ERR_NULL_ARG;
    }

    EVP_PKEY *pkey = EVP_PKEY_new_raw_private_key(
        EVP_PKEY_ED25519, NULL,
        private_key->bytes, BOWIE_SIGN_PRIVATE_LEN);
    if (pkey == NULL) {
        return BOWIE_ERR_CRYPTO;
    }

    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    if (ctx == NULL) {
        EVP_PKEY_free(pkey);
        return BOWIE_ERR_CRYPTO;
    }

    if (EVP_DigestSignInit(ctx, NULL, NULL, NULL, pkey) != 1) {
        EVP_MD_CTX_free(ctx);
        EVP_PKEY_free(pkey);
        return BOWIE_ERR_CRYPTO;
    }

    size_t sig_len = BOWIE_SIGN_SIGNATURE_LEN;

    if (EVP_DigestSign(ctx, out->bytes, &sig_len,
                       (const unsigned char *)msg, msg_len) != 1) {
        EVP_MD_CTX_free(ctx);
        EVP_PKEY_free(pkey);
        return BOWIE_ERR_CRYPTO;
    }

    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(pkey);

    if (sig_len != BOWIE_SIGN_SIGNATURE_LEN) {
        return BOWIE_ERR_CRYPTO;
    }

    return BOWIE_OK;
}

/*
 * ============================================================================
 * VERIFY
 * ============================================================================
 */

bowie_error_t bowie_sign_ed25519_verify(
    const bowie_sign_public_t *public_key,
    const void *msg, size_t msg_len,
    const bowie_sign_signature_t *signature)
{
    if (public_key == NULL || signature == NULL) {
        return BOWIE_ERR_NULL_ARG;
    }
    if (msg == NULL && msg_len > 0u) {
        return BOWIE_ERR_NULL_ARG;
    }

    EVP_PKEY *pkey = EVP_PKEY_new_raw_public_key(
        EVP_PKEY_ED25519, NULL,
        public_key->bytes, BOWIE_SIGN_PUBLIC_LEN);
    if (pkey == NULL) {
        return BOWIE_ERR_CRYPTO;
    }

    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    if (ctx == NULL) {
        EVP_PKEY_free(pkey);
        return BOWIE_ERR_CRYPTO;
    }

    if (EVP_DigestVerifyInit(ctx, NULL, NULL, NULL, pkey) != 1) {
        EVP_MD_CTX_free(ctx);
        EVP_PKEY_free(pkey);
        return BOWIE_ERR_CRYPTO;
    }

    int rc = EVP_DigestVerify(ctx, signature->bytes,
                               BOWIE_SIGN_SIGNATURE_LEN,
                               (const unsigned char *)msg, msg_len);

    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(pkey);

    if (rc == 1) {
        return BOWIE_OK;
    }
    if (rc == 0) {
        return BOWIE_ERR_SIGN_INVALID;
    }
    return BOWIE_ERR_CRYPTO;
}

/*
 * ============================================================================
 * PUBLIC FROM PRIVATE
 * ============================================================================
 *
 * An Ed25519 private key in the 64-byte OpenSSL form is the
 * seed (32 bytes) followed by the public key (32 bytes). The
 * public key is the second half of the buffer.
 *
 * The function copies the bytes directly. It does not call
 * OpenSSL, because the bytes are already the public key. A
 * caller that has a raw 32-byte seed and needs the public key
 * must derive it through OpenSSL; that is the job of keypair.c.
 */

bowie_error_t bowie_sign_ed25519_public_from_private(
    const bowie_sign_private_t *private_key,
    bowie_sign_public_t *out)
{
    if (private_key == NULL || out == NULL) {
        return BOWIE_ERR_NULL_ARG;
    }

    memcpy(out->bytes,
           private_key->bytes + BOWIE_SIGN_PUBLIC_LEN,
           BOWIE_SIGN_PUBLIC_LEN);

    return BOWIE_OK;
}

/*
 * ============================================================================
 * END OF FILE
 * ============================================================================
 */ 
